serverAddr = "114.116.87.242"
serverPort = 7000
auth.method = "token"
auth.token = "token123456"

webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

[[proxies]]
# ssh_random
name = "ssh_random_test_live"
# 代理类型
type = "tcp"
# 代理的ip
localIP = "127.0.0.1"
# 需要代理的端口
localPort = 6001
# 对外暴露的端口
remotePort = 6111

# cmd 执行.\frpc.exe -c .\frpc.toml
# name和remotePort不可以重复
#
